// Remplit les modèles avec un client FICTIF pour vérifier le rendu (fichiers écrits dans essais/, non publiés).
const fs=require('fs'),path=require('path'),PizZip=require('pizzip'),Docx=require('docxtemplater');
const paires=l=>{const r=[];for(let i=0;i<l.length;i+=2)r.push({o:l[i],e:l[i+1]||null});return r;};
const ech=[['Acompte à la signature','Signature de la lettre de mission','5 %','1 500 €'],['Diagnostic, relevé & analyse PLU','Signature de la lettre de mission — étude déjà réalisée','5 %','1 500 €'],['Esquisse (ESQ)','Validation du parti retenu par le maître d\'ouvrage','7 %','2 100 €'],['Avant-Projet Sommaire (APS)','Remise des plans et de l\'estimatif actualisé','9 %','2 700 €'],['Avant-Projet Détaillé (APD)','Remise du dossier APD et de l\'estimatif détaillé','12 %','3 600 €'],['Dossier de Permis de Construire','Dépôt du dossier en mairie de Ville-Exemple','7 %','2 100 €'],['Suivi de l\'instruction','Obtention du permis de construire','5 %','1 500 €'],['DCE / Consultation des entreprises','Remise du dossier de consultation et analyse des offres','10 %','3 000 €'],['Direction et suivi de chantier (DET)','Facturé mensuellement sur la durée du chantier','35 %','10 500 €'],['Assistance aux Opérations de Réception (AOR)','Réception des travaux','5 %','1 500 €']].map(x=>({lib:x[0],decl:x[1],pct:x[2],mt:x[3]}));
const D={num:'A2M-2026-P001',date:'25/09/2026',annee:'2026',mo_label:'Maîtres d\'ouvrage',client:'Monsieur Jean EXEMPLE et Madame Marie MODÈLE',soc:'SCI EXEMPLE',sans_soc:false,signataire:'M. Exemple et Mme Modèle',sig_client:'SCI EXEMPLE — Monsieur Jean EXEMPLE et Madame Marie MODÈLE',
adr_client:'1 rue de l\'Essai, 19000 Ville-Exemple',adr_projet:'Lieu-dit « Le Test », 19000 Ville-Exemple',terrain_a:'Le Test, 19000 Ville-Exemple — Section ZZ n°1 — Contenance 1 000 m²',cadastre_b:'Section ZZ n° 1 et 2 — Lot n° 1 du plan de division, contenance 1 000 m²',
projet:'construction d\'une maison individuelle de 150 m² environ (plain-pied)',Projet:'Construction d\'une maison individuelle de 150 m² environ (plain-pied)',
sous_titre_prop:'Mission complète — Conception à réception des travaux',sous_titre_lm:'Maîtrise d\'œuvre — Construction d\'une maison individuelle',
intro:'Dans le cadre de votre projet de construction d\'une maison individuelle de 150 m² environ (plain-pied), je vous adresse la présente proposition d\'honoraires. Ce document détaille le périmètre de ma mission, le montant proposé ainsi que les modalités de règlement.',
objet_intro:'Il s\'agit d\'une mission complète, de la conception à la réception des travaux, comprenant :',objet:['Relevé de la parcelle, diagnostic et analyse réglementaire préalable (PLU, zonage)','Esquisse (ESQ) et étude de faisabilité'],
nc_intro:'Ne sont pas comprises dans la présente proposition, et pourront faire l\'objet d\'une mission ou d\'une consultation distincte :',non_compris:['Étude de sol G2','Aménagement mobilier et décoration intérieure'],
a_taux:true,travaux:'500 000',taux:'6',taux_lib:'Taux d\'honoraires — mission complète (conception à réception des travaux)',total:'30 000',
ech_intro:'Les honoraires sont répartis selon l\'avancement de la mission, chaque phase étant facturée à son achèvement. Le poste « Direction et suivi de chantier » est facturé mensuellement sur la durée effective du chantier.',
ech:paires(ech),ech_lm:paires([{lib:'Acompte à la signature (diagnostic PLU inclus — étude déjà réalisée)',mt:'3 000 €'}].concat(ech.slice(2).map(x=>({lib:x.lib,mt:x.mt})))),
plafond:true,plafond_lignes:'les six premières lignes du tableau ci-dessus',plafond_pct:'45',plafond_mt:'13 500',plafond_solde:'16 500',plafond_solde_pct:'55',
acompte:'3 000',acompte_lettres:'trois mille euros',acompte_ref:'aux deux premières lignes de l\'échéancier ci-dessus (Acompte à la signature + Diagnostic, relevé & analyse PLU)',acompte_ref_court:'aux deux premières lignes de l\'échéancier ci-dessus',
lm_acompte_ref:'à la première ligne de l\'échéancier ci-dessus',acompte_texte:'Ce montant inclut le diagnostic, relevé et l\'analyse du PLU, déjà réalisés par ATELIER 2M en amont de la présente proposition (voir annexe 1) et facturés intégralement dès la signature, sans attendre la remise d\'un livrable complémentaire.',
delai:'15',iban:'FR76 0000 0000 0000 0000 0000 000',bic:'XXXXFRPP',titulaire:'Titulaire Exemple',
lm_intro:'La présente lettre de mission définit les conditions (texte d\'essai).',phases:['Esquisse (ESQ)','APS puis APD'],lm_fin:'La mission s\'achève à la réception des travaux et à la levée des éventuelles réserves.',limites:['Les études techniques spécifiques — voir annexe 1','L\'aménagement mobilier et la décoration intérieure'],
a_est_a:true,est_budget:'650 000',a_est_b:true,est_ht:'500 000',est_ttc:'600 000',lm_role:'ATELIER 2M intervient dans le cadre d\'une mission de conception (texte d\'essai).',
est_titre:'PROJET DE CONSTRUCTION D\'UNE MAISON INDIVIDUELLE',est_sous_titre:'Maison plain-pied — 150 m²',est_ref:'A2M-2026-P001-EST',presentation:['Premier paragraphe de présentation.','Second paragraphe.'],a_presentation:true,a_est_ctr:true,a_est_objet:true,est_objet_intro:'La mission confiée porte sur l\'ensemble du projet :',est_objet:[{sous:true,t:'Mission Permis de construire'},{p:true,t:'Relevé'},{p:true,t:'Esquisse'},{sous:true,t:'Mission Suivi de chantier'},{p:true,t:'DET / AOR'}],est_ctr_phrase:'Le détail de ces missions et leur chiffrage font l\'objet des documents « Proposition d\'honoraires » joints au présent dossier.',
total_ttc:'600 000',ratio:'4 000',surf_hab:'150',ratio_note:'visée (hors piscine)',hypothese:['Cette estimation constitue une hypothèse de travail.'],
lots:paires([{n:'1',lib:'Terrassement / VRD',part:'5,0 %',ht:'25 000 €',ttc:'30 000 €'},{n:'2',lib:'Gros œuvre',part:'30,0 %',ht:'150 000 €',ttc:'180 000 €'},{n:'3',lib:'Aléas de chantier (provision 6%)',part:'5,7 %',ht:'28 302 €',ttc:'33 962 €'}]),total_ht:'500 000',tva_taux:'20',tva:'100 000',
annexes_intro:['Au-delà du montant des travaux, un projet de construction comprend un certain nombre de postes annexes.'],annexes:paires([{lib:'Taxe d\'aménagement',mt:'10 000 €',m2:'66,67 €',obs:'Estimation'},{lib:'Raccordement eau',mt:'1 600 €',m2:'10,67 €',obs:'Tarif courant'}]),annexes_total:'11 600',budget:'611 600',budget_note:'travaux + annexes — hors honoraires de maîtrise d\'œuvre',
a_vigilance:true,vigilance:['Point de vigilance numéro un','Point numéro deux'],nature:['L\'estimation présentée constitue une évaluation prévisionnelle.'],
plu_commune:'Ville-Exemple (19000)',plu_lieudit:'Le Test',plu_cad:'Section ZZ, feuille 1, n°0001',plu_contenance:'1 000 m²',plu_doc:'PLU de Ville-Exemple',
av_n:'2',intitule:'Mission complète',contrat_ref:'proposition d\'honoraires n°A2M-2026-P001',date_signature:'12/10/2026',av_date:'20/11/2026',av_lib:'Ajout d\'un abri de jardin au programme',av_objet:['Le maître d\'ouvrage souhaite ajouter un abri de jardin de 20 m².','Les plans et le dossier de permis de construire sont modifiés en conséquence.'],montant_initial:'30\u00a0000',a_avant_prec:true,avenants_prec:'+ 1\u00a0500',av_montant:'+ 2\u00a0000',nouveau_total:'33\u00a0500',av_plus:true,av_moins:false,av_decl:'signature de l\'avenant',av_tranche:'',
sections:[{titre:'Zonage — point déterminant',blocs:[{texte:true,t:'La parcelle est en zone U.'},{puce:true,t:'Partie nord : zone U'},{alerte:true,t:'Point d\'alerte en orange italique.'}]},{titre:'Synthèse',blocs:[{texte:true,t:'Le terrain est constructible.'}]}]};
fs.mkdirSync('essais',{recursive:true});
for(const f of fs.readdirSync('../../public/modeles')){
  const zip=new PizZip(fs.readFileSync('../../public/modeles/'+f));
  const d=new Docx(zip,{paragraphLoop:true,linebreaks:true,nullGetter:()=>''});
  try{d.render(D);}catch(e){console.log('ERREUR',f,JSON.stringify(e.properties&&e.properties.errors?e.properties.errors.map(x=>x.properties.explanation):e.message));continue;}
  fs.writeFileSync('essais/'+f,d.getZip().generate({type:'nodebuffer'}));console.log('rempli',f);
}
